-- MySQL Script generated by MySQL Workbench
-- Tue Apr 24 04:52:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_cadtreesa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cadtreesa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cadtreesa` DEFAULT CHARACTER SET utf8 ;
USE `db_cadtreesa` ;

-- -----------------------------------------------------
-- Table `db_cadtreesa`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cadtreesa`.`USERS` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `rgacpf` VARCHAR(12) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `hash` VARCHAR(64) NOT NULL,
  `type` ENUM('STD', 'TCR', 'CDR') NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `rgacpf_UNIQUE` (`rgacpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cadtreesa`.`TREES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cadtreesa`.`TREES` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `specie` VARCHAR(45) NOT NULL,
  `family` VARCHAR(45) NULL,
  `cap` FLOAT NULL,
  `height` INT NULL,
  `classcup` ENUM('ampla', 'mediana', 'curta') NULL,
  `sanity` ENUM('boa', 'média', 'ruim') NULL,
  `growth` ENUM('lento', 'devagar', 'normal', 'rápido', 'muito rápido') NULL,
  `sociological` ENUM('emergente', 'superior', 'médio', 'inferior', 'isolada') NULL,
  `utilization` VARCHAR(255) NULL,
  `features` TEXT(1500) NULL,
  `image` VARCHAR(255) NULL,
  `latitude` DECIMAL(20,15) NULL,
  `longitude` DECIMAL(20,15) NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `validated` TINYINT NOT NULL,
  `id_user` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_user`),
  INDEX `fk_TREES_USERS_idx` (`id_user` ASC),
  CONSTRAINT `fk_TREES_USERS`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_cadtreesa`.`USERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cadtreesa`.`LOG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cadtreesa`.`LOG` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_user` INT UNSIGNED NOT NULL,
  `signin_dt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `signout_dt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TINYINT NOT NULL DEFAULT 0,
  `timeout` TINYINT NOT NULL DEFAULT 0,
  `ip` VARCHAR(45) NOT NULL,
  `browser` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LOG_USERS1_idx` (`id_user` ASC),
  CONSTRAINT `fk_LOG_USERS1`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_cadtreesa`.`USERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
